version: '3.9'
services:
  ui:
    build:
      context: .
      dockerfile: ./docker/ui.Dockerfile
      target: base
    ports:
      - '4200:80'
    depends_on:
      - api
    environment:
      - PROXY_URL=http://api
  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    ports:
      - '8000:80'
    environment:
      - POSTGRES_DB=games_db
      - POSTGRES_USER=games_db_user
      - POSTGRES_PASSWORD=games_db_password
      - POSTGRES_HOST=db
      - LOG_LEVEL=debug
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=games_db
      - POSTGRES_USER=games_db_user
      - POSTGRES_PASSWORD=games_db_password